sudo: required
language: perl6
perl6:
    - latest
install:
    - sudo apt-get install --install-recommends -y liquidsoap icecast2
    - sudo sed -i -e 's/ENABLE=false/ENABLE=true/' /etc/default/icecast2
    - sudo service icecast2 start
    - rakudobrew build-zef
    - zef --deps-only --/test install .
